In [6]:
import requests
import pandas as pd
import kaleido
from pathlib import Path
BASE_DIR = Path.cwd()  # project root


url_spend = "https://api.worldbank.org/v2/country/all/indicator/SH.XPD.GHED.PP.CD?date=2010:2019&format=json&per_page=20000"
url_life  = "https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?date=2010:2019&format=json&per_page=20000"

def fetch_wb(url):
    r = requests.get(url, timeout=30) 
    r.raise_for_status()              
    return r.json()[1]

In [7]:
print(BASE_DIR)

/Users/nataliam/Desktop/All/python_projects/aboba

In [8]:
spend_raw = fetch_wb(url_spend)
life_raw  = fetch_wb(url_life)


def to_df(raw, value_col):
    rows = [{"country": d["country"]["value"],
             "iso":     d["countryiso3code"],
             "year":    int(d["date"]),
             value_col: d["value"]} for d in raw]
    return pd.DataFrame(rows)

df_spend = to_df(spend_raw, "health_spend")
df_life  = to_df(life_raw,  "life_exp")

In [9]:
eu_iso = ["AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN",
          "FRA","DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX",
          "MLT","NLD","POL","PRT","ROU","SVK","SVN","ESP","SWE"]


eu_spend = df_spend[df_spend["iso"].isin(eu_iso)]

eu_life = df_life[df_life["iso"].isin(eu_iso)]

In [10]:
eu_spend.head()

     country  iso  year  health_spend
600  Austria  AUT  2019   4771.374180
601  Austria  AUT  2018   4401.698591
602  Austria  AUT  2017   4168.014161
603  Austria  AUT  2016   3971.299362
604  Austria  AUT  2015   3778.943647

In [11]:
eu_life.head()

     country  iso  year   life_exp
600  Austria  AUT  2019  81.895122
601  Austria  AUT  2018  81.692683
602  Austria  AUT  2017  81.643902
603  Austria  AUT  2016  81.641463
604  Austria  AUT  2015  81.190244

In [12]:
key_years = [2010, 2015, 2019]

In [13]:
eu_spend_keys = eu_spend[eu_spend["year"].isin(key_years)]
eu_life_keys  = eu_life[eu_life["year"].isin(key_years)]

In [14]:
dupes = eu_spend_keys[eu_spend_keys.duplicated(subset=["iso", "year"], keep=False)]
print(dupes)

Empty DataFrame
Columns: [country, iso, year, health_spend]
Index: []

In [15]:
spend_pivot = eu_spend_keys.pivot_table(index="iso", columns="year", values="health_spend", aggfunc="mean")
life_pivot  = eu_life_keys.pivot_table(index="iso", columns="year", values="life_exp", aggfunc="mean")

In [16]:
spend_pivot = spend_pivot.dropna()
life_pivot  = life_pivot.dropna()

In [17]:
spend_pivot.head()

year         2010         2015         2019
iso
AUT   3114.108095  3778.943647  4771.374180
BEL   3113.644669  3822.866962  4598.111747
BGR    584.071062   776.106471  1121.080448
CYP   1008.904367   898.312756  1694.379266
CZE   1789.428864  2099.511776  2893.933067

In [18]:
life_pivot.head()

year       2010       2015       2019
iso
AUT   80.580488  81.190244  81.895122
BEL   80.182927  80.992683  81.995122
BGR   73.512195  74.614634  75.112195
CYP   80.632000  81.464000  81.454000
CZE   77.424390  78.578049  79.229268

In [19]:


spend_pivot.columns = ["spend_2010", "spend_2015", "spend_2019"]
life_pivot.columns  = ["life_2010",  "life_2015",  "life_2019"]

df = spend_pivot.join(life_pivot, how="inner")  
print(df.shape)

(27, 6)

In [20]:
print(df.head())

      spend_2010   spend_2015   spend_2019  life_2010  life_2015  life_2019
iso
AUT  3114.108095  3778.943647  4771.374180  80.580488  81.190244  81.895122
BEL  3113.644669  3822.866962  4598.111747  80.182927  80.992683  81.995122
BGR   584.071062   776.106471  1121.080448  73.512195  74.614634  75.112195
CYP  1008.904367   898.312756  1694.379266  80.632000  81.464000  81.454000
CZE  1789.428864  2099.511776  2893.933067  77.424390  78.578049  79.229268

In [21]:

# % change in spending from 2010 to 2015
df["spend_change_pct"] = ((df["spend_2015"] - df["spend_2010"]) / df["spend_2010"]) * 100

# did spending go up or down?
df["spend_group"] = df["spend_change_pct"].apply(
    lambda x: "Increased" if x > 0 else "Decreased"
)

In [22]:

iso_to_name = {d["countryiso3code"]: d["country"]["value"] for d in spend_raw}
df["country"] = df.index.map(iso_to_name)

print(df[["country", "spend_change_pct", "spend_group", "life_2015", "life_2019"]])

             country  spend_change_pct spend_group  life_2015  life_2019
iso
AUT          Austria         21.349148   Increased  81.190244  81.895122
BEL          Belgium         22.777882   Increased  80.992683  81.995122
BGR         Bulgaria         32.878775   Increased  74.614634  75.112195
CYP           Cyprus        -10.961555   Decreased  81.464000  81.454000
CZE          Czechia         17.328597   Increased  78.578049  79.229268
DEU          Germany         26.225562   Increased  80.641463  81.292683
DNK          Denmark         11.250229   Increased  80.702439  81.451220
ESP            Spain          5.533407   Increased  82.831707  83.831707
EST          Estonia         38.126225   Increased  77.590244  78.646341
FIN          Finland         15.171376   Increased  81.480488  81.982927
FRA           France         19.488903   Increased  82.321951  82.826829
GRC           Greece        -31.493395   Decreased  81.036585  81.639024
HRV          Croatia         -2.218176   Decreased  77.275610  78.224390
HUN          Hungary         15.926462   Increased  75.568293  76.319512
IRL          Ireland          5.362085   Increased  81.453659  82.702439
ITA            Italy          0.156523   Increased  82.543902  83.497561
LTU        Lithuania         27.968923   Increased  74.321951  76.282927
LUX       Luxembourg        -10.246154   Decreased  82.292683  82.639024
LVA           Latvia         28.363070   Increased  74.480488  75.387805
MLT            Malta         39.304887   Increased  81.797561  82.658537
NLD      Netherlands          9.610850   Increased  81.509756  82.112195
POL           Poland         23.461024   Increased  77.451220  77.904878
PRT         Portugal         -6.615233   Decreased  81.124390  81.675610
ROU          Romania          6.534590   Increased  74.912195  75.607317
SVK  Slovak Republic         15.818205   Increased  76.563415  77.665854
SVN         Slovenia         11.196808   Increased  80.775610  81.529268
SWE           Sweden         55.593624   Increased  82.204878  83.109756

In [23]:
df[["life_2015", "life_2019"]] = df[["life_2015", "life_2019"]].round(2)

In [24]:
df.loc[df["country"] == "Croatia", "country"] = "Croatia*"

In [25]:
import plotly.graph_objects as go

colors = {"Increased": "#2ecc71", "Decreased": "#e74c3c"}

In [26]:
fig = go.Figure()  

legend_shown = {"Increased": False, "Decreased": False}

for _, row in df.sort_values("life_2015").iterrows():
    color = colors[row["spend_group"]]
    group = row["spend_group"]
    show = not legend_shown[group]

    fig.add_trace(go.Scatter(
        x=[row["life_2015"], row["life_2019"]],
        y=[row["country"], row["country"]],
        mode="lines",
        line=dict(color=color, width=2),
        showlegend=False
    ))

    fig.add_trace(go.Scatter(
        x=[row["life_2015"]],
        y=[row["country"]],
        mode="markers",
        marker=dict(color="white", size=10, line=dict(color=color, width=2)),
        showlegend=False
    ))

    fig.add_trace(go.Scatter(
        x=[row["life_2019"]],
        y=[row["country"]],
        mode="markers",
        marker=dict(color=color, size=10),
        name=f"Spending {group} (2010→2015)",
        showlegend=show,
        hovertemplate=f"<b>{row['country']}</b><br>2015: {row['life_2015']:.1f}<br>2019: {row['life_2019']:.1f}<br>Spending: {row['spend_change_pct']:+.1f}%<extra></extra>"
    ))

    legend_shown[group] = True

fig.update_layout(
    #title=dict(
        #text="More healthcare expenses - longer lives? On average - yes.<br><sup> The countries that increased healthcare spending gained on average 0.84 years <br> of life expectancy between 2015 and 2019 — nearly twice the gain of countries that cut spending.</sup>",
        #x=0.5,
        #xanchor="center"
    #),
    title=dict(
    text="More healthcare expenses - longer lives? On average - yes.",
    x=0.5,
    xanchor="center",
    font=dict(color="#1a2f4a")  # your dark blue
),
    xaxis_title="Life Expectancy (years)",
    yaxis_title="",
    height=800,
    plot_bgcolor="white",
    xaxis=dict(
        range=[df[["life_2015", "life_2019"]].min().min() - 0.5,
               df[["life_2015", "life_2019"]].max().max() + 0.5],
        gridcolor="#eeeeee"
    ),
    legend=dict(
        x=1.48,
        y=0.98,
        xanchor="right",
        yanchor="top"
    ),
)

# Annotation 1: source
fig.add_annotation(
    text="Source: World Bank,<br>Domestic general government<br>health expenditure (% of GDP),<br>Life expectancy at birth",
    xref="paper", yref="paper",
    x=1.4, y=-0.1,
    showarrow=False,
    font=dict(size=10, color="darkgrey"),
    xanchor="right",
    bordercolor="grey",
    borderwidth=1,
    borderpad=6,
    bgcolor="white"
)


# Annotation 2: Croatia note
fig.add_annotation(
    text="*Croatia joined the EU in 2013.        <br>Gains may reflect accession reforms        <br>rather than spending trends.        ",
    xref="paper", yref="paper",
    x=1.47, y=0.8,
    showarrow=False,
    font=dict(size=11, color="#4a6080"),
    xanchor="right",
    bgcolor="rgba(245, 241, 248, 0.85)",
    bordercolor="rgba(0,0,0,0)",
    borderpad=8
)

# Annotation 3: subtitle
fig.add_annotation(
    text="The EU countries that increased healthcare spending gained on average 0.84 years<br>of life expectancy between 2015 and 2019 — nearly twice the gain of countries that cut spending.",
    xref="paper", yref="paper",
    x=0.6, y=1.06,
    showarrow=False,
    font=dict(size=13, color="#4a6080"),
    xanchor="center",
    yanchor="top",
    bgcolor="rgba(240, 244, 248, 0.85)",
    bordercolor="rgba(0,0,0,0)",
    borderpad=8
)


                   
    
fig.show()
    
#More healthcare expenses - longer lives? On average - yes.
#The few EU countries that cut healthcare spending between 2010 and 2015 saw smaller life expectancy gains five year later.

In [27]:

df["life_change"] = df["life_2019"] - df["life_2015"]

print(df.groupby("spend_group")[["life_change"]].agg(["mean", "min", "max", "count"]).round(2))

            life_change
                   mean   min   max count
spend_group
Decreased          0.49 -0.01  0.94     5
Increased          0.84  0.45  1.96    22

In [28]:
print(df[["country", "spend_group", "life_change"]].sort_values(["spend_group", "life_change"], ascending=[True, False]))

             country spend_group  life_change
iso
HRV         Croatia*   Decreased         0.94
GRC           Greece   Decreased         0.60
PRT         Portugal   Decreased         0.56
LUX       Luxembourg   Decreased         0.35
CYP           Cyprus   Decreased        -0.01
LTU        Lithuania   Increased         1.96
IRL          Ireland   Increased         1.25
SVK  Slovak Republic   Increased         1.11
EST          Estonia   Increased         1.06
BEL          Belgium   Increased         1.01
ESP            Spain   Increased         1.00
ITA            Italy   Increased         0.96
LVA           Latvia   Increased         0.91
SWE           Sweden   Increased         0.91
MLT            Malta   Increased         0.86
DNK          Denmark   Increased         0.75
HUN          Hungary   Increased         0.75
SVN         Slovenia   Increased         0.75
AUT          Austria   Increased         0.71
ROU          Romania   Increased         0.70
CZE          Czechia   Increased         0.65
DEU          Germany   Increased         0.65
NLD      Netherlands   Increased         0.60
FRA           France   Increased         0.51
BGR         Bulgaria   Increased         0.50
FIN          Finland   Increased         0.50
POL           Poland   Increased         0.45

In [29]:
fig.write_html("in_five_years_chart.html")

In [30]:
fig.to_html(full_html=False, include_plotlyjs='cdn')

'<div>                        <script>window.PlotlyConfig = {MathJaxConfig: \'local\'};</script>\n        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.4.0.min.js" integrity="sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=" crossorigin="anonymous"></script>                <div id="bb383789-46fe-41a3-8eb1-f2d0a2b62adf" class="plotly-graph-div" style="height:800px; width:100%;"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("bb383789-46fe-41a3-8eb1-f2d0a2b62adf")) {                    Plotly.newPlot(                        "bb383789-46fe-41a3-8eb1-f2d0a2b62adf",                        [{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[74.32,76.28],"y":["Lithuania","Lithuania"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[74.32],"y":["Lithuania"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eLithuania\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 74.3\\u003cbr\\u003e2019: 76.3\\u003cbr\\u003eSpending: +28.0%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":true,"x":[76.28],"y":["Lithuania"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[74.48,75.39],"y":["Latvia","Latvia"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[74.48],"y":["Latvia"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eLatvia\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 74.5\\u003cbr\\u003e2019: 75.4\\u003cbr\\u003eSpending: +28.4%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[75.39],"y":["Latvia"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[74.61,75.11],"y":["Bulgaria","Bulgaria"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[74.61],"y":["Bulgaria"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eBulgaria\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 74.6\\u003cbr\\u003e2019: 75.1\\u003cbr\\u003eSpending: +32.9%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[75.11],"y":["Bulgaria"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[74.91,75.61],"y":["Romania","Romania"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[74.91],"y":["Romania"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eRomania\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 74.9\\u003cbr\\u003e2019: 75.6\\u003cbr\\u003eSpending: +6.5%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[75.61],"y":["Romania"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[75.57,76.32],"y":["Hungary","Hungary"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[75.57],"y":["Hungary"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eHungary\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 75.6\\u003cbr\\u003e2019: 76.3\\u003cbr\\u003eSpending: +15.9%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[76.32],"y":["Hungary"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[76.56,77.67],"y":["Slovak Republic","Slovak Republic"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[76.56],"y":["Slovak Republic"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eSlovak Republic\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 76.6\\u003cbr\\u003e2019: 77.7\\u003cbr\\u003eSpending: +15.8%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[77.67],"y":["Slovak Republic"],"type":"scatter"},{"line":{"color":"#e74c3c","width":2},"mode":"lines","showlegend":false,"x":[77.28,78.22],"y":["Croatia*","Croatia*"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#e74c3c","width":2},"size":10},"mode":"markers","showlegend":false,"x":[77.28],"y":["Croatia*"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eCroatia*\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 77.3\\u003cbr\\u003e2019: 78.2\\u003cbr\\u003eSpending: -2.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#e74c3c","size":10},"mode":"markers","name":"Spending Decreased (2010→2015)","showlegend":true,"x":[78.22],"y":["Croatia*"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[77.45,77.9],"y":["Poland","Poland"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[77.45],"y":["Poland"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003ePoland\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 77.5\\u003cbr\\u003e2019: 77.9\\u003cbr\\u003eSpending: +23.5%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[77.9],"y":["Poland"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[77.59,78.65],"y":["Estonia","Estonia"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[77.59],"y":["Estonia"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eEstonia\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 77.6\\u003cbr\\u003e2019: 78.7\\u003cbr\\u003eSpending: +38.1%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[78.65],"y":["Estonia"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[78.58,79.23],"y":["Czechia","Czechia"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[78.58],"y":["Czechia"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eCzechia\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 78.6\\u003cbr\\u003e2019: 79.2\\u003cbr\\u003eSpending: +17.3%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[79.23],"y":["Czechia"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[80.64,81.29],"y":["Germany","Germany"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[80.64],"y":["Germany"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eGermany\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 80.6\\u003cbr\\u003e2019: 81.3\\u003cbr\\u003eSpending: +26.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[81.29],"y":["Germany"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[80.7,81.45],"y":["Denmark","Denmark"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[80.7],"y":["Denmark"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eDenmark\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 80.7\\u003cbr\\u003e2019: 81.5\\u003cbr\\u003eSpending: +11.3%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[81.45],"y":["Denmark"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[80.78,81.53],"y":["Slovenia","Slovenia"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[80.78],"y":["Slovenia"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eSlovenia\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 80.8\\u003cbr\\u003e2019: 81.5\\u003cbr\\u003eSpending: +11.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[81.53],"y":["Slovenia"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[80.99,82.0],"y":["Belgium","Belgium"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[80.99],"y":["Belgium"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eBelgium\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.0\\u003cbr\\u003e2019: 82.0\\u003cbr\\u003eSpending: +22.8%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[82.0],"y":["Belgium"],"type":"scatter"},{"line":{"color":"#e74c3c","width":2},"mode":"lines","showlegend":false,"x":[81.04,81.64],"y":["Greece","Greece"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#e74c3c","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.04],"y":["Greece"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eGreece\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.0\\u003cbr\\u003e2019: 81.6\\u003cbr\\u003eSpending: -31.5%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#e74c3c","size":10},"mode":"markers","name":"Spending Decreased (2010→2015)","showlegend":false,"x":[81.64],"y":["Greece"],"type":"scatter"},{"line":{"color":"#e74c3c","width":2},"mode":"lines","showlegend":false,"x":[81.12,81.68],"y":["Portugal","Portugal"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#e74c3c","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.12],"y":["Portugal"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003ePortugal\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.1\\u003cbr\\u003e2019: 81.7\\u003cbr\\u003eSpending: -6.6%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#e74c3c","size":10},"mode":"markers","name":"Spending Decreased (2010→2015)","showlegend":false,"x":[81.68],"y":["Portugal"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[81.19,81.9],"y":["Austria","Austria"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.19],"y":["Austria"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eAustria\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.2\\u003cbr\\u003e2019: 81.9\\u003cbr\\u003eSpending: +21.3%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[81.9],"y":["Austria"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[81.45,82.7],"y":["Ireland","Ireland"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.45],"y":["Ireland"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eIreland\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.5\\u003cbr\\u003e2019: 82.7\\u003cbr\\u003eSpending: +5.4%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[82.7],"y":["Ireland"],"type":"scatter"},{"line":{"color":"#e74c3c","width":2},"mode":"lines","showlegend":false,"x":[81.46,81.45],"y":["Cyprus","Cyprus"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#e74c3c","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.46],"y":["Cyprus"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eCyprus\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.5\\u003cbr\\u003e2019: 81.5\\u003cbr\\u003eSpending: -11.0%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#e74c3c","size":10},"mode":"markers","name":"Spending Decreased (2010→2015)","showlegend":false,"x":[81.45],"y":["Cyprus"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[81.48,81.98],"y":["Finland","Finland"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.48],"y":["Finland"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eFinland\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.5\\u003cbr\\u003e2019: 82.0\\u003cbr\\u003eSpending: +15.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[81.98],"y":["Finland"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[81.51,82.11],"y":["Netherlands","Netherlands"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.51],"y":["Netherlands"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eNetherlands\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.5\\u003cbr\\u003e2019: 82.1\\u003cbr\\u003eSpending: +9.6%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[82.11],"y":["Netherlands"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[81.8,82.66],"y":["Malta","Malta"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[81.8],"y":["Malta"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eMalta\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 81.8\\u003cbr\\u003e2019: 82.7\\u003cbr\\u003eSpending: +39.3%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[82.66],"y":["Malta"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[82.2,83.11],"y":["Sweden","Sweden"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[82.2],"y":["Sweden"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eSweden\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 82.2\\u003cbr\\u003e2019: 83.1\\u003cbr\\u003eSpending: +55.6%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[83.11],"y":["Sweden"],"type":"scatter"},{"line":{"color":"#e74c3c","width":2},"mode":"lines","showlegend":false,"x":[82.29,82.64],"y":["Luxembourg","Luxembourg"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#e74c3c","width":2},"size":10},"mode":"markers","showlegend":false,"x":[82.29],"y":["Luxembourg"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eLuxembourg\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 82.3\\u003cbr\\u003e2019: 82.6\\u003cbr\\u003eSpending: -10.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#e74c3c","size":10},"mode":"markers","name":"Spending Decreased (2010→2015)","showlegend":false,"x":[82.64],"y":["Luxembourg"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[82.32,82.83],"y":["France","France"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[82.32],"y":["France"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eFrance\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 82.3\\u003cbr\\u003e2019: 82.8\\u003cbr\\u003eSpending: +19.5%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[82.83],"y":["France"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[82.54,83.5],"y":["Italy","Italy"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[82.54],"y":["Italy"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eItaly\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 82.5\\u003cbr\\u003e2019: 83.5\\u003cbr\\u003eSpending: +0.2%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[83.5],"y":["Italy"],"type":"scatter"},{"line":{"color":"#2ecc71","width":2},"mode":"lines","showlegend":false,"x":[82.83,83.83],"y":["Spain","Spain"],"type":"scatter"},{"marker":{"color":"white","line":{"color":"#2ecc71","width":2},"size":10},"mode":"markers","showlegend":false,"x":[82.83],"y":["Spain"],"type":"scatter"},{"hovertemplate":"\\u003cb\\u003eSpain\\u003c\\u002fb\\u003e\\u003cbr\\u003e2015: 82.8\\u003cbr\\u003e2019: 83.8\\u003cbr\\u003eSpending: +5.5%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","marker":{"color":"#2ecc71","size":10},"mode":"markers","name":"Spending Increased (2010→2015)","showlegend":false,"x":[83.83],"y":["Spain"],"type":"scatter"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201

In [31]:
# Static PNG — for embedding in README
fig.write_image(
    BASE_DIR/"outputs"/"in_five_years.png",
    width=1200, height=600, scale=2,
)

# Interactive HTML — for the grader to hover/zoom
fig.write_html(
    BASE_DIR/"outputs"/"in_five_years_interact.html"
)

/var/folders/jq/wxn09tld1nlgws0gvk_bcwz00000gn/T/ipykernel_79824/3799917453.py:2: DeprecationWarning:
Support for Kaleido versions less than 1.0.0 is deprecated and will be removed after September 2025.
Please upgrade Kaleido to version 1.0.0 or greater (`pip install 'kaleido>=1.0.0'` or `pip install 'plotly[kaleido]'`).

  fig.write_image(